[colors.primary]
# background = "#1a1a1a"

[cursor.style]
shape = "Block"

[font]
size = 14

[font.normal]
# family = "MxPlus IBM VGA 8x16"
# family = "MxPlus IBM VGA 8x14"
# family = "MxPlus HP 100LX 6x8"
# family = "Mx437 HP 100LX 6x8"
# family = "InputMonoCondensed"
# family = "Code New Roman Nerd Font"
# family = "IosevkaComfyMotion"
# family = "IosevkaComfyMotion"
# family = "Commit Mono"
# family = "RobotoCondensed"
family = "UbuntuMono"
style = "Regular"
[font.bold]
# family = "MxPlus HP 100LX 10x11"
#family = "Code New Roman Nerd Font"
style = "Bold"
[font.bold_italic]
# family = "Code New Roman Nerd Font"
style = "Bold Italic"
[font.italic]
# family = "Code New Roman Nerd Font"
style = "Italic"

[window]
# # decoration = "none"
opacity = 0.9
#
[window.padding]
x = 25
y = 6
